steps:
- name: 'node:10'
  args: ['npm', 'install']
  dir: worker
- name: 'node:10'
  args: ['npm', 'test']
  dir: worker
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'trace']
  dir: worker
